@extends('layouts.app')

@section('title', 'AI Briefs')

@section('content')
<div class="py-6 px-4 sm:px-6 lg:px-8">
    <div class="mb-6">
        <div class="flex flex-wrap items-center justify-between gap-4">
            <div>
                <h1 class="text-2xl font-bold text-gray-900">📋 AI Briefs</h1>
                <p class="text-gray-600">Daily strategic briefs generated by AI</p>
                @if(isset($lastBrief))
                    <p class="text-sm text-gray-500 mt-1">
                        Last generated: {{ $lastBrief->created_at->diffForHumans() }}
                        @if($lastBrief->confidence_score)
                            · Confidence: {{ $lastBrief->confidence_score }}%
                        @endif
                    </p>
                @endif
            </div>
            <div class="flex flex-wrap gap-2">
                <form action="{{ route('briefs.generate') }}" method="POST" id="generateBriefForm">
                    @csrf
                    <button type="submit" 
                            id="generateBriefBtn"
                            class="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition flex items-center gap-2">
                        <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 10V3L4 14h7v7l9-11h-7z"/>
                        </svg>
                        <span id="generateBtnText">Generate Brief Now</span>
                    </button>
                </form>
                <button onclick="window.location.reload()" class="px-4 py-2 bg-gray-200 text-gray-700 rounded-lg hover:bg-gray-300 transition">
                    🔄 Refresh
                </button>
            </div>
        </div>
    </div>

    <!-- Stats Cards -->
    <div class="grid grid-cols-1 md:grid-cols-4 gap-4 mb-6">
        <div class="bg-white p-4 rounded-lg shadow-sm border border-gray-200">
            <p class="text-sm text-gray-500">Total Briefs</p>
            <p class="text-2xl font-bold text-gray-900">{{ $totalBriefs ?? 0 }}</p>
        </div>
        <div class="bg-white p-4 rounded-lg shadow-sm border border-gray-200">
            <p class="text-sm text-gray-500">This Week</p>
            <p class="text-2xl font-bold text-blue-600">{{ $briefsThisWeek ?? 0 }}</p>
        </div>
        <div class="bg-white p-4 rounded-lg shadow-sm border border-gray-200">
            <p class="text-sm text-gray-500">Latest Confidence</p>
            <p class="text-2xl font-bold text-green-600">
                {{ isset($lastBrief) && $lastBrief->confidence_score ? $lastBrief->confidence_score . '%' : 'N/A' }}
            </p>
        </div>
        <div class="bg-white p-4 rounded-lg shadow-sm border border-gray-200">
            <p class="text-sm text-gray-500">Total Actions</p>
            <p class="text-2xl font-bold text-purple-600">
                {{ isset($briefs) ? $briefs->sum(fn($b) => $b->actions()->count()) : 0 }}
            </p>
        </div>
    </div>

    <!-- Loading/Status Message -->
    <div id="generateStatus" class="hidden mb-4 p-4 bg-blue-50 border border-blue-200 rounded-lg">
        <div class="flex items-center space-x-3">
            <div class="animate-spin rounded-full h-5 w-5 border-b-2 border-blue-600"></div>
            <span class="text-blue-700" id="generateStatusText">Generating AI brief... This may take 30-60 seconds.</span>
        </div>
    </div>

    <!-- Briefs List -->
    <div class="space-y-6">
        @forelse($briefs as $brief)
            <div class="bg-white rounded-lg shadow-sm border border-gray-200 overflow-hidden hover:shadow-md transition">
                <div class="px-6 py-4 border-b border-gray-200 flex flex-wrap items-center justify-between gap-4">
                    <div>
                        <div class="flex items-center space-x-3">
                            <h2 class="text-lg font-semibold text-gray-900">
                                Brief for {{ \Carbon\Carbon::parse($brief->brief_date)->format('F j, Y') }}
                            </h2>
                            <span class="text-xs px-2 py-1 bg-blue-100 text-blue-800 rounded-full">
                                {{ $brief->ai_provider ?? 'Unknown' }}
                            </span>
                        </div>
                        <div class="flex flex-wrap items-center space-x-3 mt-1">
                            @if($brief->confidence_score)
                                <span class="text-xs px-2 py-1 bg-green-100 text-green-800 rounded-full">
                                    Confidence: {{ $brief->confidence_score }}%
                                </span>
                            @endif
                            @if($brief->estimated_revenue_impact)
                                <span class="text-xs px-2 py-1 bg-yellow-100 text-yellow-800 rounded-full">
                                    Impact: ${{ number_format($brief->estimated_revenue_impact, 2) }}
                                </span>
                            @endif
                            <span class="text-xs text-gray-400">
                                {{ $brief->created_at->diffForHumans() }}
                            </span>
                            <span class="text-xs text-gray-400">
                                {{ $brief->actions()->count() }} actions
                            </span>
                        </div>
                    </div>
                    <a href="{{ route('briefs.show', $brief->id) }}" 
                       class="px-4 py-2 text-sm bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition">
                        View Full Brief
                    </a>
                </div>
                <div class="p-6">
                    <div class="prose max-w-none">
                        <p class="text-gray-700 whitespace-pre-wrap">{{ $brief->strategic_diagnosis }}</p>
                    </div>
                    <div class="mt-4 pt-4 border-t border-gray-200">
                        <a href="{{ route('actions.queue') }}" class="text-sm text-blue-600 hover:text-blue-800">
                            View in Action Queue →
                        </a>
                    </div>
                </div>
            </div>
        @empty
            <div class="bg-white rounded-lg shadow-sm border border-gray-200 overflow-hidden">
                <div class="p-12 text-center">
                    <div class="text-6xl mb-4">📋</div>
                    <h3 class="text-lg font-medium text-gray-900 mb-2">No Briefs Generated Yet</h3>
                    <p class="text-gray-500">Briefs are generated daily at 6:00 AM.</p>
                    <p class="text-gray-400 text-sm mt-1">Click the "Generate Brief Now" button to create one manually.</p>
                    <form action="{{ route('briefs.generate') }}" method="POST" class="mt-4">
                        @csrf
                        <button type="submit" class="px-6 py-3 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition">
                            🚀 Generate First Brief
                        </button>
                    </form>
                </div>
            </div>
        @endforelse
    </div>
</div>
@endsection

@push('scripts')
<script>
document.addEventListener('DOMContentLoaded', function() {
    const form = document.getElementById('generateBriefForm');
    if (!form) return;
    
    form.addEventListener('submit', function(e) {
        e.preventDefault();
        
        const btn = document.getElementById('generateBriefBtn');
        const btnText = document.getElementById('generateBtnText');
        const statusDiv = document.getElementById('generateStatus');
        const statusText = document.getElementById('generateStatusText');
        
        // Disable button and show loading
        btn.disabled = true;
        btnText.textContent = 'Generating...';
        statusDiv.classList.remove('hidden');
        statusText.textContent = 'Generating AI brief... This may take 30-60 seconds.';
        statusDiv.className = 'mb-4 p-4 bg-blue-50 border border-blue-200 rounded-lg';
        
        // Get CSRF token
        const csrfToken = document.querySelector('meta[name="csrf-token"]')?.content || '';
        
        // Submit via AJAX
        fetch(form.action, {
            method: 'POST',
            headers: {
                'X-CSRF-TOKEN': csrfToken,
                'Accept': 'application/json',
                'Content-Type': 'application/json',
            },
            body: JSON.stringify({}),
        })
        .then(async response => {
            const contentType = response.headers.get('content-type');
            if (!contentType || !contentType.includes('application/json')) {
                throw new Error('Server returned non-JSON response.');
            }
            if (!response.ok) {
                const text = await response.text();
                throw new Error(`Server error (${response.status}): ${text.substring(0, 100)}`);
            }
            return response.json();
        })
        .then(data => {
            if (data.success) {
                statusText.textContent = '✅ ' + data.message;
                statusDiv.className = 'mb-4 p-4 bg-green-50 border border-green-200 rounded-lg';
                
                // Show brief details
                if (data.actions_count !== undefined) {
                    statusText.textContent += ` (${data.actions_count} actions created)`;
                }
                
                // Reload after 1.5 seconds
                setTimeout(() => {
                    window.location.reload();
                }, 1500);
            } else {
                statusText.textContent = '❌ ' + data.message;
                statusDiv.className = 'mb-4 p-4 bg-red-50 border border-red-200 rounded-lg';
                btn.disabled = false;
                btnText.textContent = 'Generate Brief Now';
            }
        })
        .catch(error => {
            console.error('Fetch error:', error);
            statusText.textContent = '❌ Error: ' + error.message;
            statusDiv.className = 'mb-4 p-4 bg-red-50 border border-red-200 rounded-lg';
            btn.disabled = false;
            btnText.textContent = 'Generate Brief Now';
        });
    });
});
</script>
@endpush